//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Studythings/LangBuilder/src/dotNet/LangBuilder/Transpiler/Grammar/TranspilerGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class TranspilerGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, Newline=2, Whitespace=3, Label=4;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "Newline", "Whitespace", "Label"
	};


	public TranspilerGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TranspilerGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'cat'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "Newline", "Whitespace", "Label"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TranspilerGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TranspilerGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x6', '$', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x5', '\x3', '\x12', '\n', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '\x15', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x6', '\x4', '\x1A', '\n', '\x4', '\r', '\x4', '\xE', '\x4', '\x1B', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x6', '\x5', '!', '\n', '\x5', 
		'\r', '\x5', '\xE', '\x5', '\"', '\x2', '\x2', '\x6', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\x3', '\x2', '\x4', '\x4', '\x2', '\v', 
		'\v', '\"', '\"', '\x5', '\x2', '\x32', ';', '\x43', '\\', '\x63', '|', 
		'\x2', '\'', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\v', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\a', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\t', ' ', '\x3', '\x2', '\x2', '\x2', '\v', '\f', '\a', '\x65', 
		'\x2', '\x2', '\f', '\r', '\a', '\x63', '\x2', '\x2', '\r', '\xE', '\a', 
		'v', '\x2', '\x2', '\xE', '\x4', '\x3', '\x2', '\x2', '\x2', '\xF', '\x11', 
		'\a', '\xF', '\x2', '\x2', '\x10', '\x12', '\a', '\f', '\x2', '\x2', '\x11', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x11', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x12', '\x15', '\x3', '\x2', '\x2', '\x2', '\x13', '\x15', '\a', 
		'\f', '\x2', '\x2', '\x14', '\xF', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x15', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\x17', '\b', '\x3', '\x2', '\x2', '\x17', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x1A', '\t', '\x2', '\x2', '\x2', '\x19', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x19', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x1E', '\b', '\x4', '\x2', '\x2', '\x1E', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '!', '\t', '\x3', '\x2', '\x2', ' ', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '!', '\"', '\x3', '\x2', '\x2', '\x2', '\"', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\"', '#', '\x3', '\x2', '\x2', '\x2', '#', '\n', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x2', '\x11', '\x14', '\x1B', '\"', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
