//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Studythings/LangBuilder/src/dotNet/LangBuilder/Transpiler/Grammar/TranspilerGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TranspilerGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ITranspilerGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] TranspilerGrammarParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] TranspilerGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.construct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstruct([NotNull] TranspilerGrammarParser.ConstructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] TranspilerGrammarParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.blockStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStart([NotNull] TranspilerGrammarParser.BlockStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.blockEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockEnd([NotNull] TranspilerGrammarParser.BlockEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.constructDeclarationBlockStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructDeclarationBlockStart([NotNull] TranspilerGrammarParser.ConstructDeclarationBlockStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TranspilerGrammarParser.constructDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructDeclaration([NotNull] TranspilerGrammarParser.ConstructDeclarationContext context);
}
